repos:
  - repo: https://github.com/koalaman/shellcheck
    rev: v0.10.0
    hooks:
      - id: shellcheck
        name: shellcheck (bin scripts)
        files: ^bin/|^scripts/
        types: [shell]
  - repo: https://github.com/mvdan/sh
    rev: v3.10.0
    hooks:
      - id: shfmt
        args: ["-i", "2", "-ci"]
        files: ^bin/|^scripts/
