#!/bin/bash
echo "=== Development Environment Check ==="
echo ""
echo "System Info:"
echo "- OS: $(lsb_release -d | cut -f2)"
echo "- Kernel: $(uname -r)"
echo ""
echo "Languages & Runtimes:"
echo "- Node: $(node --version 2>/dev/null || echo 'Not installed')"
echo "- Python: $(python --version 2>/dev/null || echo 'Not installed')"
echo "- Java: $(java --version 2>&1 | head -n 1)"
echo ""
echo "Package Managers:"
echo "- npm: $(npm --version 2>/dev/null || echo 'Not installed')"
echo "- yarn: $(yarn --version 2>/dev/null || echo 'Not installed')"
echo "- pnpm: $(pnpm --version 2>/dev/null || echo 'Not installed')"
echo "- pip: $(pip --version 2>/dev/null || echo 'Not installed')"
echo ""
echo "Development Tools:"
echo "- Git: $(git --version)"
echo "- Docker: $(docker --version 2>/dev/null || echo 'Not installed')"
echo "- Docker Compose: $(docker compose version 2>/dev/null || echo 'Not installed')"
echo ""
echo "Databases (checking if installed, not if running):"
echo "- PostgreSQL: $(psql --version 2>/dev/null || echo 'Not installed')"
echo "- MySQL: $(mysql --version 2>/dev/null || echo 'Not installed')"
echo "- MongoDB: $(mongod --version 2>/dev/null | head -n 1 || echo 'Not installed')"
echo "- Redis: $(redis-server --version 2>/dev/null || echo 'Not installed')"
echo ""
echo "GPU/CUDA:"
echo "- NVIDIA Driver: $(nvidia-smi --query-gpu=driver_version --format=csv,noheader 2>/dev/null || echo 'Not available')"
echo "- CUDA: $(nvcc --version 2>/dev/null | grep release || echo 'Not installed')"
